name: Build and push

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'master'
  schedule:
    - cron: '17 8 * * 0'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12, 3.13]
    env:
      latest: 3.13

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ghcr.io/${{ github.repository }}
        flavor: |
          latest=false
        # generate Docker tags based on the following events/attributes
        tags: |
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') && matrix.python-version == env.latest }}
          type=ref,event=branch,enable=${{ matrix.python-version == env.latest }}
          type=ref,event=pr,enable=${{ matrix.python-version == env.latest }}
          type=ref,event=branch,suffix=-${{ matrix.python-version }}
          type=ref,event=pr,suffix=-${{ matrix.python-version }}
          type=match,value=${{ matrix.python-version }},pattern=\d+
          type=match,value=${{ matrix.python-version }},pattern=\d+\.\d+
          # also provide tag starting with semver of the image itself,
          # in the same way Python devcontainer does it, eg. 1.0-3.13
          type=semver,pattern={{version}},suffix=-${{ matrix.python-version }}
          type=semver,pattern={{major}}.{{minor}},suffix=-${{ matrix.python-version }}
          type=semver,pattern={{major}},suffix=-${{ matrix.python-version }}
          type=sha,enable=${{ matrix.python-version == env.latest }}
          type=sha,suffix=-${{ matrix.python-version }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        build-args: |
          PYTHONVERSION=${{ matrix.python-version }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache
        cache-to: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache,mode=max
